# Generated by Django 6.1.1 on 2026-09-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenero', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cancion',
            options={'ordering': ['-popularidad'], 'verbose_name_plural': 'canciones'},
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='genero',
        ),
        migrations.AddField(
            model_name='cancion',
            name='playlist',
            field=models.ManyToManyField(related_name='canciones', to='catalogo.playlist'),
        ),
    ]
