# Generated by Django 6.1.1 on 2026-10-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
